"""
Thread-Safe Investigation Context for Enterprise AI Investigation Platform.

Replaces ad-hoc parameter passing by storing investigation requests, execution plans,
evidence registries, agent outputs, execution timings, confidence progression, and
shared agent state in a thread-safe context container.
"""

from datetime import datetime, timezone
import threading
from typing import Any, Dict, List, Optional
import uuid

from agents.core.logger import get_agent_logger
from agents.orchestrator_ai.evidence_registry import EvidenceRegistry
from agents.orchestrator_ai.investigation_models import (
    InvestigationPlan,
    InvestigationRequest,
)

logger = get_agent_logger("InvestigationContext")


class InvestigationContext:
    """
    Thread-safe context object shared across investigation agent steps.
    """

    def __init__(
        self,
        request: InvestigationRequest,
        plan: Optional[InvestigationPlan] = None,
        evidence_registry: Optional[EvidenceRegistry] = None,
    ) -> None:
        self.context_id = str(uuid.uuid4())
        self._request = request
        self._plan = plan
        self._evidence_registry = evidence_registry or EvidenceRegistry()
        self._agent_outputs: Dict[str, Any] = {}
        self._execution_timings: Dict[str, float] = {}
        self._confidence_evolution: List[Dict[str, Any]] = []
        self._verification_results: Dict[str, Any] = {}
        self._operator_metadata: Dict[str, Any] = dict(request.context_hints)
        self._shared_state: Dict[str, Any] = {}
        self._created_at = datetime.now(timezone.utc)
        self._lock = threading.RLock()

    @property
    def request(self) -> InvestigationRequest:
        """The initial investigation request."""
        return self._request

    @property
    def plan(self) -> Optional[InvestigationPlan]:
        """The investigation plan generated by PlannerAgent."""
        with self._lock:
            return self._plan

    @plan.setter
    def plan(self, plan: InvestigationPlan) -> None:
        """Set or update the investigation plan."""
        with self._lock:
            self._plan = plan

    @property
    def evidence_registry(self) -> EvidenceRegistry:
        """Central Evidence Registry instance."""
        return self._evidence_registry

    @property
    def results(self) -> Dict[str, Any]:
        """Dictionary of agent outputs for backward compatibility with ExecutionContext."""
        return self._agent_outputs

    @property
    def shared_state(self) -> Dict[str, Any]:
        """Thread-safe copy of shared state dictionary."""
        with self._lock:
            return dict(self._shared_state)

    def set_agent_output(self, agent_name: str, output: Any, timing_ms: float = 0.0) -> None:
        """
        Record output payload and execution duration for an agent.
        """
        with self._lock:
            self._agent_outputs[agent_name] = output
            if timing_ms > 0.0:
                self._execution_timings[agent_name] = timing_ms
            logger.debug(f"Context updated with output from '{agent_name}' ({timing_ms:.2f}ms)")

    def get_agent_output(self, agent_name: str) -> Optional[Any]:
        """Fetch recorded output payload for an agent."""
        with self._lock:
            return self._agent_outputs.get(agent_name)

    def get_all_agent_outputs(self) -> Dict[str, Any]:
        """Fetch copy of all agent outputs."""
        with self._lock:
            return dict(self._agent_outputs)

    def get_execution_timings(self) -> Dict[str, float]:
        """Fetch copy of execution timings map."""
        with self._lock:
            return dict(self._execution_timings)

    def record_confidence_sample(self, agent_name: str, confidence: float, rationale: str = "") -> None:
        """
        Record confidence progression checkpoint.
        """
        sample = {
            "timestamp": datetime.now(timezone.utc).isoformat(),
            "agent": agent_name,
            "confidence": max(0.0, min(1.0, confidence)),
            "rationale": rationale,
        }
        with self._lock:
            self._confidence_evolution.append(sample)
            logger.debug(f"Confidence recorded by '{agent_name}': {confidence:.2f}")

    def get_confidence_progression(self) -> List[Dict[str, Any]]:
        """Fetch copy of confidence evolution list."""
        with self._lock:
            return list(self._confidence_evolution)

    def get_latest_confidence(self) -> float:
        """Get most recent confidence score recorded in progression, or 0.0."""
        with self._lock:
            if not self._confidence_evolution:
                return 0.0
            return self._confidence_evolution[-1]["confidence"]

    def set_shared(self, key: str, value: Any) -> None:
        """Set value in shared thread-safe state dictionary."""
        with self._lock:
            self._shared_state[key] = value

    def get_shared(self, key: str, default: Any = None) -> Any:
        """Get value from shared thread-safe state dictionary."""
        with self._lock:
            return self._shared_state.get(key, default)

    def add_verification_result(self, key: str, result: Any) -> None:
        """Add verification check result to context."""
        with self._lock:
            self._verification_results[key] = result

    def get_verification_results(self) -> Dict[str, Any]:
        """Fetch copy of verification results dictionary."""
        with self._lock:
            return dict(self._verification_results)
