"""
Strongly Typed Pydantic V2 Domain Models for Enterprise AI Investigation Orchestrator.

Provides request/result contracts, DAG node/edge structures, investigation plans,
evidence requirements, execution summaries, and system statistics.
All models support serialization and persistence.
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional
import uuid

from pydantic import BaseModel, Field, ConfigDict


class ComplexityLevel(str, Enum):
    """Classification of investigation request complexity."""

    SIMPLE = "SIMPLE"
    MODERATE = "MODERATE"
    COMPLEX = "COMPLEX"
    CRITICAL = "CRITICAL"


class PlanStatus(str, Enum):
    """Lifecycle status of investigation plan nodes and overall execution."""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"


class DependencyType(str, Enum):
    """Types of execution dependencies between agent nodes."""

    HARD = "HARD"
    SOFT = "SOFT"
    CONDITIONAL = "CONDITIONAL"


class InvestigationRequest(BaseModel):
    """Request payload received from network operators or automated triggers."""

    model_config = ConfigDict(frozen=False)

    request_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique request ID")
    operator_query: str = Field(..., description="Natural language or structured query")
    device_id: Optional[str] = Field(default=None, description="Target device identifier if applicable")
    interface: Optional[str] = Field(default=None, description="Target interface name if applicable")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Additional context parameters")
    operator_id: str = Field(default="system", description="Identifier of operator or requesting component")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    priority: int = Field(default=1, ge=1, le=5, description="Priority level 1-5")
    context_hints: Dict[str, Any] = Field(default_factory=dict, description="Domain context hints")


class EvidenceRequirement(BaseModel):
    """Declarative specification of evidence needed to fulfill investigation."""

    model_config = ConfigDict(frozen=False)

    requirement_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    description: str = Field(..., description="Goal description of the required evidence")
    required_agent: str = Field(..., description="Name of Atomic Agent designated to produce evidence")
    evidence_type: str = Field(..., description="Category tag of expected evidence")
    is_mandatory: bool = Field(default=True, description="Whether failure to produce fails investigation")


class AgentExecutionPlan(BaseModel):
    """Plan for an individual Atomic Agent execution step."""

    model_config = ConfigDict(frozen=False)

    agent_name: str = Field(..., description="Unique name of target Atomic Agent")
    depends_on: List[str] = Field(default_factory=list, description="Agent names that must run prior")
    expected_output_schema: Optional[str] = Field(default=None, description="Expected schema identifier")
    retry_count: int = Field(default=2, ge=0, description="Allowed retry attempts on failure")
    timeout_seconds: float = Field(default=30.0, gt=0.0, description="Max execution duration in seconds")
    mandatory: bool = Field(default=True, description="Must succeed for overall plan success")
    parameters: Dict[str, Any] = Field(default_factory=dict, description="Agent input parameters")


class InvestigationStage(BaseModel):
    """Stage grouping of agent execution steps in an investigation workflow."""

    model_config = ConfigDict(frozen=False)

    stage_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str = Field(..., description="Descriptive stage name")
    agent_plans: List[AgentExecutionPlan] = Field(default_factory=list, description="Agents in stage")
    parallel_execution: bool = Field(default=True, description="Whether agents run concurrently")
    stop_on_failure: bool = Field(default=False, description="Stop stage if an agent fails")


class InvestigationPlan(BaseModel):
    """Complete structured plan generated by PlannerAgent."""

    model_config = ConfigDict(frozen=False)

    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    request_id: str = Field(..., description="Associated request ID")
    query_classification: ComplexityLevel = Field(default=ComplexityLevel.MODERATE)
    estimated_cost: float = Field(default=1.0, ge=0.0, description="Estimated execution cost unit")
    target_confidence: float = Field(default=0.85, ge=0.0, le=1.0, description="Target confidence threshold")
    stages: List[InvestigationStage] = Field(default_factory=list)
    required_agents: List[str] = Field(default_factory=list)
    required_evidence: List[EvidenceRequirement] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ExecutionNode(BaseModel):
    """Node in an ExecutionGraph representing an agent task execution."""

    model_config = ConfigDict(frozen=False)

    node_id: str = Field(..., description="Unique node identifier (usually agent name)")
    agent_name: str = Field(..., description="Name of Atomic Agent to execute")
    dependencies: List[str] = Field(default_factory=list, description="Prerequisite node IDs")
    status: PlanStatus = Field(default=PlanStatus.PENDING)
    result: Optional[Dict[str, Any]] = Field(default=None)
    error: Optional[str] = Field(default=None)
    duration_ms: float = Field(default=0.0, ge=0.0)
    retry_count: int = Field(default=0, ge=0)
    max_retries: int = Field(default=2, ge=0)
    mandatory: bool = Field(default=True)
    output_payload: Optional[Any] = Field(default=None)


class ExecutionEdge(BaseModel):
    """Edge in an ExecutionGraph representing dependency relation."""

    model_config = ConfigDict(frozen=False)

    source_node: str = Field(..., description="Prerequisite node ID")
    target_node: str = Field(..., description="Dependent node ID")
    dependency_type: DependencyType = Field(default=DependencyType.HARD)


class ExecutionGraphModel(BaseModel):
    """Serializable representation of an ExecutionGraph DAG."""

    model_config = ConfigDict(frozen=False)

    graph_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    request_id: str = Field(...)
    nodes: Dict[str, ExecutionNode] = Field(default_factory=dict)
    edges: List[ExecutionEdge] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)


class EvidenceProvenance(str, Enum):
    """Controlled provenance origin category for evidence items."""

    OBSERVED = "OBSERVED"
    PREDICTED = "PREDICTED"
    INFERRED = "INFERRED"
    HISTORICAL = "HISTORICAL"
    SIMULATION = "SIMULATION"


class EvidenceRelationship(str, Enum):
    """Relationship of evidence item to primary investigation conclusion."""

    SUPPORTING = "SUPPORTING"
    CONTRADICTING = "CONTRADICTING"
    UNRESOLVED = "UNRESOLVED"
    NEUTRAL = "NEUTRAL"


class EvidenceReference(BaseModel):
    """Registered unit of evidence collected during an investigation."""

    model_config = ConfigDict(frozen=False)

    evidence_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    source_agent: str = Field(..., description="Agent or service that produced this evidence")
    evidence_type: str = Field(..., description="Evidence classification tag")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Evidence confidence score")
    provenance: str = Field(default="OBSERVED", description="Controlled provenance label (OBSERVED, PREDICTED, INFERRED, HISTORICAL, SIMULATION)")
    relationship: str = Field(default="SUPPORTING", description="Evidence relationship (SUPPORTING, CONTRADICTING, UNRESOLVED, NEUTRAL)")
    device_id: Optional[str] = Field(default=None)
    affected_entity: Optional[str] = Field(default=None, description="Target entity or component affected")
    linked_decision: Optional[str] = Field(default=None, description="Downstream conclusion or decision supported/affected")
    summary: Optional[str] = Field(default=None, description="Human-readable factual summary of evidence")
    incident_id: Optional[str] = Field(default=None)
    topology_ref: Optional[Dict[str, Any]] = Field(default=None)
    runbook_ref: Optional[Dict[str, Any]] = Field(default=None)
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    payload: Dict[str, Any] = Field(default_factory=dict)
    parent_evidence_ids: List[str] = Field(default_factory=list, description="Lineage links")


class InvestigationEvidenceLineage(BaseModel):
    """Strongly-typed, read-only unified investigation evidence lineage report."""

    model_config = ConfigDict(frozen=False)

    investigation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    target_entity: str = Field(..., description="Target device, interface, or incident entity")
    evidence_count: int = Field(default=0, ge=0)
    supporting_count: int = Field(default=0, ge=0)
    contradicting_count: int = Field(default=0, ge=0)
    unresolved_count: int = Field(default=0, ge=0)
    top_contributors: List[Dict[str, Any]] = Field(default_factory=list, description="Aggregated metrics by producing agent")
    timeline: List[EvidenceReference] = Field(default_factory=list, description="Chronological evidence items")
    decision_linkages: List[Dict[str, Any]] = Field(default_factory=list, description="Linkages to downstream decisions")
    why_this_decision: Dict[str, Any] = Field(default_factory=dict, description="Factual factor breakdown of the primary decision")
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ExecutionSummary(BaseModel):
    """Execution performance metrics for a completed investigation."""

    model_config = ConfigDict(frozen=False)

    total_agents: int = Field(default=0, ge=0)
    executed_agents: int = Field(default=0, ge=0)
    skipped_agents: int = Field(default=0, ge=0)
    failed_agents: int = Field(default=0, ge=0)
    total_duration_ms: float = Field(default=0.0, ge=0.0)
    parallelism_factor: float = Field(default=1.0, ge=0.0)


class InvestigationStatistics(BaseModel):
    """Aggregated historical metrics across investigations."""

    model_config = ConfigDict(frozen=False)

    request_count: int = Field(default=0, ge=0)
    success_rate: float = Field(default=0.0, ge=0.0, le=1.0)
    avg_duration_ms: float = Field(default=0.0, ge=0.0)
    total_evidence_collected: int = Field(default=0, ge=0)


class InvestigationResult(BaseModel):
    """Final merged investigation output payload returned to operator."""

    model_config = ConfigDict(frozen=False)

    investigation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    request_id: str = Field(...)
    plan_id: str = Field(...)
    status: PlanStatus = Field(..., description="Final investigation status")
    summary: str = Field(..., description="Human-readable executive summary")
    evidence_references: List[EvidenceReference] = Field(default_factory=list)
    merged_findings: Dict[str, Any] = Field(default_factory=dict)
    agent_outputs: Dict[str, Any] = Field(default_factory=dict)
    execution_summary: ExecutionSummary = Field(default_factory=ExecutionSummary)
    overall_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    completed_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
