frr version 10.0
frr defaults traditional
hostname branch3-uplink
no ipv6 forwarding
!
interface eth1
 description ISP-A Primary WAN Point-to-Point
 ip address 10.10.1.2/30
!
interface eth2
 description ISP-B Backup WAN Point-to-Point
 ip address 10.10.2.2/30
!
ip route 0.0.0.0/0 10.10.1.1 10
ip route 0.0.0.0/0 10.10.2.1 20
!
line vty
!
