frr version 10.0
frr defaults traditional
hostname hub
no ipv6 forwarding
!
interface eth1
 description Link to Branch1
 ip address 10.10.30.1/30
!
interface eth2
 description ISP-B Backup Link to Branch3-Uplink
 ip address 10.10.2.1/30
!
ip route 10.10.1.0/30 10.10.30.2
!
line vty
!
