"""
Failover Package Entrypoint for NOC Copilot.

Exports atomic agent, domain services, approval manager, adapters, prechecks, verifier,
rollback engine, typed network control plane abstractions, and domain models.
"""

from agents.failover.approval_manager import ApprovalManager
from agents.failover.authorized_execution_adapter import AuthorizedNetworkAdapter
from agents.failover.dry_run_adapter import DryRunExecutionAdapter
from agents.failover.execution_adapter import IExecutionAdapter, INetworkProviderDelegate
from agents.failover.failover_agent import FailoverAgent
from agents.failover.failover_models import (
    ActualOutcome,
    AdaptiveDecisionLearningResult,
    ApprovalStatus,
    ControlPlaneNotConfiguredError,
    ExecutionMode,
    ExecutionPlan,
    ExecutionResult,
    ExecutionRisk,
    ExecutionStatus,
    ExecutionStep,
    FailoverApproval,
    FailoverResult,
    FailureReason,
    LearningClassification,
    PreExecutionCheck,
    PredictedOutcome,
    ProductionExecutionDisabledError,
    RollbackResult,
    RollbackStatus,
    UnauthorizedTargetError,
    VerificationCheck,
    VerificationResult,
    VerificationStatus,
)
from agents.failover.failover_service import FailoverService
from agents.failover.frr_control_plane import FRRControlPlane
from agents.failover.network_control_plane import (
    ControlPlaneDriverType,
    ControlPlaneResponse,
    ControlPlaneStatus,
    FailbackProviderRequest,
    FailoverProviderRequest,
    INetworkControlPlane,
    NotConfiguredControlPlane,
    PathStateRequest,
    RouteVerificationRequest,
    SwitchInterfaceRequest,
    TypedControlPlaneDelegate,
)
from agents.failover.post_execution_verifier import PostExecutionVerifier
from agents.failover.pre_execution_validator import PreExecutionValidator
from agents.failover.production_control_plane import (
    DryRunProductionControlPlane,
    GNMIControlPlane,
    IProductionControlPlane,
    MockTransportServer,
    NETCONFControlPlane,
    NotConfiguredProductionControlPlane,
    validate_endpoint_profile,
)
from agents.failover.production_models import (
    BFDState,
    BFDTelemetrySignal,
    DeviceEndpointProfile,
    NOSVendor,
    OC_BFD_STATE,
    OC_INTERFACE_CONFIG,
    OC_INTERFACE_STATE,
    OC_NEXT_HOP,
    OC_STATIC_DEFAULT_ROUTE,
    OC_STATIC_ROUTE_METRIC,
    OpenConfigBFDPeer,
    OpenConfigInterfaceState,
    OpenConfigMutation,
    OpenConfigQuery,
    OpenConfigStaticRoute,
    TransportProtocol,
    TransportSessionState,
    TransportStatus,
)
from agents.failover.quorum_gate import (
    BreakGlassRequest,
    IChangeWindowProvider,
    MaintenanceWindow,
    NotConfiguredChangeWindowProvider,
    ProductionAuthorizationDecision,
    ProductionAuthorizationQuorumEngine,
    QuorumApprovalSeat,
    QuorumDecision,
    TestChangeWindowProvider,
)
from agents.failover.rollback_engine import RollbackEngine

__all__ = [
    "FailoverAgent",
    "FailoverService",
    "ApprovalManager",
    "PreExecutionValidator",
    "IExecutionAdapter",
    "INetworkProviderDelegate",
    "DryRunExecutionAdapter",
    "AuthorizedNetworkAdapter",
    "PostExecutionVerifier",
    "RollbackEngine",
    "ExecutionMode",
    "ApprovalStatus",
    "ExecutionStatus",
    "VerificationStatus",
    "RollbackStatus",
    "ExecutionRisk",
    "FailureReason",
    "FailoverApproval",
    "PreExecutionCheck",
    "ExecutionStep",
    "ExecutionPlan",
    "ExecutionResult",
    "VerificationCheck",
    "VerificationResult",
    "RollbackResult",
    "FailoverResult",
    "LearningClassification",
    "PredictedOutcome",
    "ActualOutcome",
    "AdaptiveDecisionLearningResult",
    "ProductionExecutionDisabledError",
    "ControlPlaneNotConfiguredError",
    "UnauthorizedTargetError",
    "ControlPlaneDriverType",
    "ControlPlaneStatus",
    "FailoverProviderRequest",
    "FailbackProviderRequest",
    "SwitchInterfaceRequest",
    "PathStateRequest",
    "RouteVerificationRequest",
    "ControlPlaneResponse",
    "INetworkControlPlane",
    "NotConfiguredControlPlane",
    "FRRControlPlane",
    "TypedControlPlaneDelegate",
    "NOSVendor",
    "TransportProtocol",
    "BFDState",
    "DeviceEndpointProfile",
    "BFDTelemetrySignal",
    "OpenConfigQuery",
    "OpenConfigMutation",
    "OC_INTERFACE_STATE",
    "OC_INTERFACE_CONFIG",
    "OC_STATIC_DEFAULT_ROUTE",
    "OC_STATIC_ROUTE_METRIC",
    "OC_NEXT_HOP",
    "OC_BFD_STATE",
    "IProductionControlPlane",
    "NotConfiguredProductionControlPlane",
    "DryRunProductionControlPlane",
    "GNMIControlPlane",
    "NETCONFControlPlane",
    "MockTransportServer",
    "TransportStatus",
    "TransportSessionState",
    "OpenConfigInterfaceState",
    "OpenConfigStaticRoute",
    "OpenConfigBFDPeer",
    "validate_endpoint_profile",
    "QuorumDecision",
    "MaintenanceWindow",
    "IChangeWindowProvider",
    "NotConfiguredChangeWindowProvider",
    "TestChangeWindowProvider",
    "BreakGlassRequest",
    "QuorumApprovalSeat",
    "ProductionAuthorizationDecision",
    "ProductionAuthorizationQuorumEngine",
]
