frr version 10.0
frr defaults traditional
hostname rtr-01
no ipv6 forwarding
!
interface eth1
 description Link to Firewall (fw-01)
 ip address 10.10.20.2/30
!
interface eth2
 description ISP-A Primary Link to Branch3-Uplink
 ip address 10.10.1.1/30
!
ip route 10.10.2.0/30 10.10.20.1
!
line vty
!
